version: '3.4'

networks:
  Rakaposhi-network:

services:
  rakaposhiapp:
    image: rakaposhi
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - DB_NAME=ParbatDB
    - DB_PASSWORD=MyPass@1234
    - DB_SERVER=db
    - DB_USERNAME=sa
    - DB_TYPE=SQL
    - TRUSTED=False
    build:
      context: ./TestingApp/
      dockerfile: Dockerfile
    ports:
    - "8081:80"
    networks:
      - Rakaposhi-network
